### PR TITLE
Use customElements.get for version gathering

### PR DESCRIPTION
**Pull request by platosha**
Connected to vaadin/components-team-tasks#329

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-usage-statistics/15)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-usage-statistics/15)*

**Comment by platosha** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-usage-statistics.js, line 74 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-usage-statistics/15#-L9BUmQt3ZQ_rLHYJAjM:-L9EdgyfEExLsf-Llzh6:bc9o2ks) ([raw file](https://github.com/vaadin/vaadin-usage-statistics/blob/5a55efe8d96407ec6027ea1dccc21cb4c37e8754/vaadin-usage-statistics.js#L74)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Is this here by mistake?
</blockquote></details>

Yes. It’s impossible to extract Polymer 3 version at this point AFAIK, so removed.

---

*[vaadin-usage-statistics.js, line 100 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-usage-statistics/15#-L9BUz3KDTBqjORGfhxG:-L9EduO_2A2fb6mQ9IjB:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-usage-statistics/blob/5a55efe8d96407ec6027ea1dccc21cb4c37e8754/vaadin-usage-statistics.js#L100)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

vaadin-horizontal-layout + vaadin-vertical-layout
</blockquote></details>

Done

---

*[vaadin-usage-statistics.js, line 104 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-usage-statistics/15#-L9BV2lfCS5q_YoIx5LI:-L9EdvKz185cFUI5mRGf:b-896fix) ([raw file](https://github.com/vaadin/vaadin-usage-statistics/blob/5a55efe8d96407ec6027ea1dccc21cb4c37e8754/vaadin-usage-statistics.js#L104)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

also vaadin-tab
</blockquote></details>

Done.

---

*[vaadin-usage-statistics.js, line 105 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-usage-statistics/15#-L9BVt6c624mPt_dT6l3:-L9Edvno10jQ6Mp41nkl:b-896fix) ([raw file](https://github.com/vaadin/vaadin-usage-statistics/blob/5a55efe8d96407ec6027ea1dccc21cb4c37e8754/vaadin-usage-statistics.js#L105)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

also vaadin-password-field, vaadin-text-area
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-usage-statistics/15)*

**Comment by platosha** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-usage-statistics.js, line 74 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-usage-statistics/15#-L9BUmQt3ZQ_rLHYJAjM:-L9EeobNCpHWGbF0ChyK:b-896fix) ([raw file](https://github.com/vaadin/vaadin-usage-statistics/blob/5a55efe8d96407ec6027ea1dccc21cb4c37e8754/vaadin-usage-statistics.js#L74)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Yes. It’s impossible to extract Polymer 3 version at this point AFAIK, so removed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-usage-statistics/15)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-usage-statistics/15#-:-L9EfAvX1liPpXycbOdI:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-usage-statistics/15)*

**Pull request merged**
